# .air.toml
# Watch all .go files in the project
[build]
  cmd = "go build -o main ."
  bin = "main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  delay = 1000

[log]
  time = true
