services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-validation-app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - CGO_ENABLED=0
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=gouser
      - DB_PASS=gopassword
      - DB_NAME=go_validation
    volumes:
      - .:/app
      - /app/tmp

  db:
    image: mysql:8.0
    container_name: go-validation-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: go_validation
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gopassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "gouser", "-pgopassword"]
      timeout: 20s
      retries: 10

volumes:
  db_data: